### ISSUE TITLE
Develop help information with "-h" or "--help" flags

### ISSUE THREAD

**Issue by andre-baIbi** [balbi-uff/4chanScrapper#20]
Some important info so that the user doesn't necessarily go back to GitHub to search after instructions. Maybe even include a tip like "For simple instructions, type "-h" or "--help" before executing the program.

**Comment by sijilo** [comment]
@balbi-uff   added an pr please review (added help command to show the readme.md  contents in console) 
thanks
 ref : https://github.com/balbi-uff/4chanScrapper/pull/22
